<?php

/**
 * ViperCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    viper
 * @subpackage model
 * @author     Pedro Hernandez <phpleo
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class ViperCompany extends BaseViperCompany
{
}
