<?php

/**
 * VpUserstory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    viper
 * @subpackage model
 * @author     Pedro Hernandez <phpleo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VpUserstory extends BaseVpUserstory
{

    public function __toString()
    {
        return $this->getContent();
    }

}