vp_task:
  class: sfDoctrineRouteCollection
  options:
    model:                VpTask
    module:               task
    prefix_path:          /task
    column:               id
    with_wildcard_routes: true

vp_userstory:
  class: sfDoctrineRouteCollection
  options:
    model:                VpUserstory
    module:               userstory
    prefix_path:          /userstory
    column:               id
    with_wildcard_routes: true

vp_project:
  class: sfDoctrineRouteCollection
  options:
    model:                VpProject
    module:               project
    prefix_path:          /project
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }

# companies
viper_company_index:
  url:   /company
  param: { module: company, action: index }

viper_company_show:
  url:   /company/show/:slug
  param: { module: company, action: show }

#
# sfGuard
#

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request-password
  param: { module: sfGuardAuth, action: password }


#
# generic rules
# please, remove them by adding more specific rules
#
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
