<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/11/28 13:24:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=192.168.1.33;dbname=viper_dev',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
